#server config
server:
  port: 8080
  servlet:
    context-path: /hello-world


#mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.wusiq


# database connection configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: ${DB_ACCOUNT}
    password: ${DB_PASSWORD}
    schema: classpath:hello-ddl.sql
    data: classpath:hello-dml.sql
    initialization-mode: always
  aop:
    proxy-target-class: true

#log config
logging:
  config: classpath:log4j2.xml
  level:
    com.wusiq: debug
    com.wusiq.dao: debug

